[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# PEP 621 dependencies declaration
# adapt to your dependencies manager
[project]
dependencies = [
    "mkdocstrings[python]>=0.18",
]