[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# PEP 621 dependencies declaration
# adapt to your dependencies manager
[project]
name = "attention_lense"
version = "0.0.1"
dependencies = [
    "mkdocstrings[python]>=0.18",
]
